# Generated by Django 4.2.5 on 2023-09-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="storage_box",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tenant",
            field=models.IntegerField(),
        ),
    ]
