# Generated by Django 4.2.5 on 2023-09-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=254, verbose_name='First name')),
                ('last_name', models.CharField(max_length=254, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('picture', models.ImageField(upload_to='profile_picture')),
            ],
        ),
        migrations.CreateModel(
            name='StorageBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_type', models.CharField(choices=[('GARAGE_BOX', 'Garage'), ('CELLAR', 'Cellar'), ('ATTIC', 'Attic'), ('ROOM', 'Room'), ('HANGAR_WAREHOUSE', 'Hangar / Warehouse'), ('PARKING', 'parking spot')], max_length=32, verbose_name="Type d'espace")),
                ('title', models.CharField(max_length=512, verbose_name='Ad title')),
                ('slug', models.SlugField(editable=False, max_length=128, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('surface', models.IntegerField(blank=True, default=1, null=True, verbose_name='Surface (m²)')),
                ('street_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='N°')),
                ('route', models.CharField(blank=True, max_length=512, null=True, verbose_name='route')),
                ('additional_address', models.TextField(blank=True, null=True, verbose_name='additional address')),
                ('postal_code', models.CharField(max_length=32, verbose_name='postal code')),
                ('city', models.CharField(max_length=32, verbose_name='city')),
                ('image_1', models.ImageField(upload_to='box_picture')),
                ('image_2', models.ImageField(upload_to='box_picture')),
                ('image_3', models.ImageField(upload_to='box_picture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_place.profile', verbose_name='owner')),
            ],
        ),
    ]
